export const GET_PRODUCTS: string = `query{
    products{
      data{
        id
        attributes{
          description
          name
          slug
          price
          availability
          categories{
            data{
              id
              attributes{
                gender
                type
              }
            }
          }
          image{
            data{
              attributes{
                formats
              }
            }
          }
        }
      }
    }
  }
  `;

export const GET_PRODUCT: string = `query getProduct($id: ID!) {
  products(filters: {id: {eq: $id}}) {
    data{
      attributes{
          description
          name
          slug
          price
          availability
          categories{
            data{
              id
              attributes{
                gender
                type
              }
            }
          }
          image{
            data{
              attributes{
                formats
              }
            }
          }
        }
    }
  }
}
`;